/* gui.c generated by valac 0.32.1, the Vala compiler
 * generated from gui.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



void gui_run (gchar** args, int args_length1);


void gui_run (gchar** args, int args_length1) {
	GtkWindow* window = NULL;
	GtkWindow* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	_g_object_unref0 (window);
}



